version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
