version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile  # 新しいDockerfileのパス
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
