openapi: 3.0.1
info:
 title: kakeibo-api
 description: golangを利用した家計簿API
 version: 1.0.0

paths:
  /v1/getUserInformation/{userID}:
    get:
      description: ユーザー情報取得
      parameters:
        - name: userID       # パラメータ名
          in: path           # パスパラメータとして指定
          required: true     # 必須パラメータ
          schema:
            type: string     # パラメータの型
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    example: 'test_user'
                  mail_address:
                    type: string
                    example: 'sample@test.com'
