openapi: 3.0.1
info:
 title: sample-api
 description: golangサンプルAPI
 version: 1.0.0

paths:
  /v1/getmessage/{id}:
    get:
      summary: テストAPI
      parameters:
        - name: id           # パラメータ名
          in: path           # パスパラメータとして指定
          required: true     # 必須パラメータ
          schema:
            type: string     # パラメータの型
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string # 配列の要素の型
